#spring:
#    h2:
#        console:
#            enabled: true
#            path: /h2-console
#    datasource:
#        driverClassName: org.h2.Driver
#        url: jdbc:h2:mem:testdb
#        username: sa
#        password:
#    jpa:
#        database-platform: org.hibernate.dialect.H2Dialect
#        hibernate:
#            ddl-auto: update
#        show-sql: true
#        format-sql: true
#    flyway:
#        enabled: true
#        locations: classpath:db/migration
#        baselineOnMigrate: true
#
#logging:
#    level:
#        root: INFO
#        org.springframework.web: INFO
#        org.hibernate: INFO

server:
    port: 8080

spring:
    application:
        name: catalog
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/catalog
        username: cataloguser
        password: catalogpass
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        hibernate:
            ddl-auto: validate
    h2:
        console:
            enabled: false
    flyway:
        enabled: true
        locations: classpath:db/migration
        validate-on-migrate: true

api:
    security:
        token:
            secret: Zk5osQLbp;B$7XP)

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html

logging:
    level:
        root: INFO