spring:
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:testdb
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        hibernate:
            ddl-auto: validate
    flyway:
        enabled: true
        locations: classpath:db/migration
        validate-on-migrate: true

springdoc:
    swagger-ui:
        path: /swagger-ui.html

logging:
    level:
        root: DEBUG