name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
        
jobs:
  
  app_build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: setup java
        uses: actions/setup-java@v3
        with: 
          distribution: 'temurin'
          java-version: '17'
      
      - name: cache maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven
           
      - name: build project
        run: mvn clean install -DskipTests
        
  docker_login_build_push:
    needs: app_build
    runs-on: ubuntu-latest
    steps:
      - name: login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: build and push docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/catalog:latest
          file: ./Dockerfile
          context: .
    
  app_upload_artifact:
    needs: app_build
    runs-on: ubuntu-latest
    steps: 
      - name: upload maven artifact
        uses: actions/upload-artifact@v3
        with:
          name: packaged-application
          path: target/*.jar